### ISSUE TITLE
CHANGELOG?

### ISSUE THREAD

**Issue by NLueg** [pIvan/ngx-color-picker#57]
Hey there! First of all, thank you for your plugin. 
I am using it for quite a long time in my Ionic-App, and it's working without any issues for two years.

For me, it's very important to have an overview of what libraries changed since the last version.
As you don't write a custom changelog and don't tag releases, I always look into the commits which were made since the last version. This is actually even harder, as you don't tag the releases you make.

This is something I have in mind for a long time and just wanted to tell you about my problems, as you can't change it if you never hear it 😄 It would at least be very cool, if you could tag a release, as the comparison is much easier then.

Thanks!

**Comment by pIvan** [comment]
Hi @NLueg,

I agree with you about the importance of an library overview, 
it's not an excuse, but since I didn't have time to write a changelog in the beginning, I kind of forgot about it later. :)

I used to put tags on library [file-upload](https://github.com/pIvan/file-upload), but unfortunately not here.
I will try to find some time to do both, and I will definitely keep this in mind for future improvements.

Everyone is certainly welcome to participate in the improvements to the library ;)

Thank you for pointing out absence of tags and changelog

**Comment by NLueg** [comment]
Hey @pIvan thanks for your fast response! 
I totally understand that! Writing the changelog is not the funniest work, and when the release is finally finished it can be quite annoying. But unfortunately, it's the only way to tell someone what happened here 😄 

And sure, if I find anything which not working or could be improved, I will provide you with an PR. Thanks for mentioning.
